export const components = ({ handleFields = () => {} }) => [
  {
    type: 'input',
    value: 'firstName',
    behaviours: { onChange: handleFields('firstName') },
    defaultValue: 'firstName',
    placeholder: 'First Name',
    isHasItems: false,
  },
  {
    type: 'input',
    value: 'lastName',
    behaviours: { onChange: handleFields('lastName') },
    defaultValue: 'lastName',
    placeholder: 'Last Name',
    isHasItems: false,
  },
  {
    type: 'input',
    value: 'email',
    behaviours: { onChange: handleFields('email') },
    defaultValue: 'email',
    placeholder: 'Email',
    isHasItems: false,
  },
  {
    type: 'input',
    value: 'role',
    behaviours: { onChange: handleFields('role') },
    defaultValue: 'role',
    placeholder: 'Access Role',
    isHasItems: false,
  },
  {
    type: 'input',
    value: 'currentCourse',
    behaviours: { onChange: handleFields('currentCourse') },
    defaultValue: 'currentCourse',
    placeholder: 'Current Course',
    isHasItems: false,
  },
  // {
  //   type: 'select',
  //   value: 'users',
  //   behaviours: { onChange: handleFields('users') },
  //   defaultValue: 'users',
  //   placeholder: 'Users',
  //   isHasItems: true,
  //   listName: 'clients',
  // },
];
